In [ ]:
print('hello world')

hello world


In [1]:
#indentation
if 4>1:
  print('4 is greater')

4 is greater


In [5]:
#comments
# for single line
print('Azan')
#for multiline comments
print("Muhammad Azan")

Azan
Muhammad Azan


In [9]:
#variable
x=67
y="amna"
z= 'Azan'
print(x)
print(y)
print(z)

67
amna
Azan


In [10]:
x=69
x="Azan"
print(x)

Azan


In [12]:
#casting (specifing data type of variables)
x=str('Azan')
y=int(6)
z=float(6.9)
print (x,y,z)

Azan 6 6.9


In [14]:
#getting data type
x=69
y='Azan'
z=6.9
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>


In [15]:
#case sensitive
a=69
A="Azan"
print ( A,a)

Azan 69


In [16]:
#multiple values to multiple variables
x,y,z=('Mercedes','BMW','Toyota')
print(x,y,z)

Mercedes BMW Toyota


In [17]:
#one value to multiple values
x=y=z = ("Black Nigga")
print(x,y,z)

Black Nigga Black Nigga Black Nigga


In [19]:
#unpacking
Cars=['Mercedes','BMW','Toyota']
a,b,c= Cars
print(a,b,c)

Mercedes BMW Toyota


In [20]:
#output variables
x='Mercedes is best'
print(x)
#using multiple variables
x='Mercedes'
y='is '
z='best'
print(x,y,z)

Mercedes is best
Mercedes is  best


In [21]:
#output varibles with '+' operator
#for charchters:
x='Mercedes'
y='is '
z='best'
print(x+y+z)
#for numbers it is used sum operator
x=39
y=30
print(x+y)


Mercedesis best
69


In [ ]:
#global variables (that are created outside of a function)
x='it is a '
def myfunc():
  print(x+ 'big door')
myfunc()

# using both global and local variables
x=' great'
def myfunc():
  x=' good'
  print('python is' +x)
myfunc()

print('python is' +x)

#using global keyword
def myfunc():
  global x
  x='awesome'
myfunc()
print('python is ' +x)

it is a big door
python is good
python is great
python is awesome


In [24]:
#datatypes
   #int
x=1
y=937390234
z=-862932
print(type(x))
print(type(y))
print(type(z))

#float
a=83.66
b=-88.2
print(type(a))
print(type(b))
s=76e2
t=-93.78e4
print(type(s))
print(type(t))

#complex
m=5+7j
n=-3j
o=9j
print(type(m))
print(type(n))
print(type(o))

#string
p='Azan'
q='Shan'
r='Manan'
print(type(p))
print(type(q))
print(type(r))

#import random
import random
print(random.randrange(1,69))




<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'complex'>
<class 'complex'>
<class 'complex'>
<class 'str'>
<class 'str'>
<class 'str'>
66


In [26]:
#strings
print("Muhammad Azan")

#Qoutes inside quotes (the inside strings do not match outside strings)
print("His name is 'Shan'")
print('i am a "Legend"')

#Assigning string to a variable
a='I hate you'
print(a)

#multiline strings(you can use both double or single qoutes)
a='''i have many
     hobbies like:
     playing,drawing'''
print(a)


#strings as arrays
a="hello world"
print(a[1])

#looping via string
for x in 'banana':
  print(x)

#string length
p='new world'
print(len(p))

#cheak string
life="life is hard"
print('life' in life)


Muhammad Azan
His name is 'Shan'
i am a "Legend"
I hate you
i have many
     hobbies like:
     playing,drawing
e
b
a
n
a
n
a
9
True


In [ ]:
#slicing strings
a='hello world'
print(a[3:7])

#slice from start
b='hello world'
print(b[:8])

#slice from end
c='hello world'
print(c[2:])

#negative indexing
d='hello world'
print(d[-7:-3])

lo w
hello wo
llo world
o wo


In [27]:
#Modify string

#upper case
a="Mercedes is best"
print(a.upper())

#lower case
a="Mercedes is best"
print(a.lower())

#remove whitespace
b=" Mercedes is best   "
print(b.strip())

#replace string
c="Mercedes is best"
print(c.replace("e", "E"))

#split string
d="Mercedes is best"
print(d.split(" "))

MERCEDES IS BEST
mercedes is best
Mercedes is best
MErcEdEs is bEst
['Mercedes', 'is', 'best']


In [ ]:
#string concatination(combine)

a="new"
b="sentence"
c=a + " " + b
print(c)


new sentence


In [30]:
#format string
#f-string
a=20
b="My age is {a}"
print(b)

#placeholder and modifiers
#placehlders-----> can contains func,variable,operations
#modifiers------> it uses ":" to fomat value (within {})

# for adding 3 decimal place
p=69
txt=f"the price is {p:.3f} rs"
print(txt)

# for maths operations
p=47
txt=f"the price is {47 * 6} rs"
print(txt)

My age is {a}
the price is 69.000 rs
the price is 282 rs


In [31]:
#escape charcter(for inserting an illegeal charcter in a string)
# like to add qoutes in qoutes

a="this is a very \"beautiful\" car"
print(a)

this is a very "beautiful" car


In [32]:
#boolean(for getting ans as true or fasle)

print(3==3)
print(6>1)
print(4<9)

#printing message on based on truee or fasle
a=40
b=65
if a>b :
  print("a is greater than b")
else:
  print("b is greater than b")

#evualting variables and values
#it returns true if there is some content or the value is not zero or the empty set

#returns true
print(bool("BMW"))
print(bool(69))
print(bool(['CAR','orange']))

#returns false
print(bool(0))
print(bool({}))
print(bool(''))

#obj with func __len__ also returns false
class myclass():
  def __len__(ok):
    return 0
myobj=myclass()
print(bool(myobj))



True
True
True
b is greater than b
True
True
True
False
False
False
False


In [ ]:
#operators

print(5+6)
print(8/4)

#operator precedence
print((6+3)-(6+3))
print(6*4+2)

11
2.0
0
26


In [34]:
#list (ordered,changeable,allow duplicate values)
mylist=['Mercedes','BMW']
print(mylist)

#allow duplicates
thelist=['Mercedes','BMW','Volvo','Audi','Audi']
print(thelist)

#list length
mylist=['Mercedes','BMW','Volvo']
print(len(mylist))

#list items (different datatypes)
mylist=['Mercedes',69,False]
print(mylist)
print(type(mylist))

#list constructor
thelist=(('Mercedes','BMW','Volvo','Audi','Audi'))
print(thelist)

['Mercedes', 'BMW']
['Mercedes', 'BMW', 'Volvo', 'Audi', 'Audi']
3
['Mercedes', 69, False]
<class 'list'>
('Mercedes', 'BMW', 'Volvo', 'Audi', 'Audi')


In [35]:
#access list items
#first item has 0 index
thislist=['Mercedes','BMW','Volvo']
print(thislist[1])

#negative indexing (starts from last)
thislist=['Mercedes','BMW','Volvo']
print(thislist[-3])

#range of index
thislist=['Mercedes','BMW','Volvo','Audi','Audi']
print(thislist[3:7])

#range of negative index
mylist=['Mercedes','BMW','Volvo','Audi','Audi']
print(mylist[-6:-2])

#Check if Item Exists
mylist=['Mercedes','BMW','Volvo','Audi','Audi']
if 'BMW' in mylist:
  print("yes, 'BMW' is in list")

BMW
Mercedes
['Audi', 'Audi']
['Mercedes', 'BMW', 'Volvo']
yes, 'BMW' is in list


In [37]:
#change list items
#change by index
mylist=['Mercedes','BMW','Volvo']
mylist[0]='Porche'
print(mylist)

#chnage list by range
mylist=['Mercedes','BMW','Volvo']
mylist[0:2]='Hundai','Hunda','Nisaan'
print(mylist)

#insert new item
mylist=['Mercedes','BMW','Volvo']
mylist.insert(3,'Toyota')
print(mylist)

#add list items
#append func(to add the end of the list)
thislist=['Mercedes','BMW','Volvo']
thislist.append('Nissan')
print(thislist)

#insert func(to add at the specific index)
thislist=['Mercedes','BMW','Volvo']
thislist.insert(2,'Nissan')
print(thislist)

#extend list (to add/append list,dict or tuples)
#by list
thelist=['Mercedes','BMW','Volvo']
mylist=['Hundai','Hunda','Nisaan']
thelist.extend(mylist)
print(thelist)
#by tuple
thelist=['Mercedes','BMW','Volvo']
thistuple=('Hundai','Hunda','Nisaan')
thelist.extend(thistuple)
print(thelist)

['Porche', 'BMW', 'Volvo']
['Hundai', 'Hunda', 'Nisaan', 'Volvo']
['Mercedes', 'BMW', 'Volvo', 'Toyota']
['Mercedes', 'BMW', 'Volvo', 'Nissan']
['Mercedes', 'BMW', 'Nissan', 'Volvo']
['Mercedes', 'BMW', 'Volvo', 'Hundai', 'Hunda', 'Nisaan']
['Mercedes', 'BMW', 'Volvo', 'Hundai', 'Hunda', 'Nisaan']


In [39]:
#remove list items
#remove() fuc *** to remove specific item***
thislist=['Mercedes','BMW','Volvo']
thislist.remove('Volvo')
print(thislist)

#pop() func *** remove specific index***
thislist=['Mercedes','BMW','Volvo']
thislist.pop(2)
print(thislist)

#del() *** also removes specific index***
thislist=['Mercedes','BMW','Volvo']
del thislist [0]
print(thislist)
#del can also delt complete list
thislist=['Mercedes','BMW','Volvo']
del thislist

#clear list ***empties the list
thislist=['Mercedes','BMW','Volvo']
thislist.clear()
print(thislist)

['Mercedes', 'BMW']
['Mercedes', 'BMW']
['BMW', 'Volvo']
[]


In [40]:
#loop list
#for loop
mylist=['Mercedes','BMW','Volvo']
for x in mylist:
  print(x)
  #loop through index
mylist=['Mercedes','BMW','Volvo']
for x in range(len(mylist)):
  print(mylist[x])
#while loop
thislist=['Mercedes','BMW','Volvo']
i=0
while i< len(thislist):
  print(thislist[i])
  i=i+1

#Looping Using List Comprehension
#shorthand for loop
thislist=['Mercedes','BMW','Volvo']
_=[print(x) for x in thislist]


Mercedes
BMW
Volvo
Mercedes
BMW
Volvo
Mercedes
BMW
Volvo
Mercedes
BMW
Volvo


In [41]:
#list comprehenshion
vehicles=['Mercedes','BMW','Volvo']
newlist=[]
for x in vehicles:
  if 'M' in x:
    newlist.append(x)
print(newlist)

#Iterable
mylist=[x for x in range(10)]
print(mylist)

['Mercedes', 'BMW']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [42]:
#list sorting

#Alphanumerically list sorting ***ascending***

#alphabetticaly:
thislist=['Mercedes','BMW','Volvo']
thislist.sort()
print(thislist)

#numerical:
mylist=[5,7,6,9,3,0]
mylist.sort()
print(mylist)

#Sort Descending
#alphabetticaly:
thislist=['Mercedes','BMW','Volvo']
thislist.sort(reverse=True)
print(thislist)

#numerical:
mylist=[5,7,6,9,3,0]
mylist.sort(reverse=True)
print(mylist)

#Customize Sort Function
# ***finding a number closer to 65 in sequence   ***abs: is a built-in func use to find absolute value
def myfunc(n):
  return abs(n-65)
thislist=[55,76,89,66,56,65]
thislist.sort(key=myfunc)
print(thislist)

#Case Insensitive Sort
thislist=['Mercedes','BMW','Volvo']
thislist.sort()
print(thislist)
#for printing small alphabets first:
thislist=['Mercedes','BMW','Volvo']
thislist.sort(key=str.lower)
print(thislist)

#reversing list
thislist=['Mercedes','BMW','Volvo']
thislist.reverse()
print(thislist)

['BMW', 'Mercedes', 'Volvo']
[0, 3, 5, 6, 7, 9]
['Volvo', 'Mercedes', 'BMW']
[9, 7, 6, 5, 3, 0]
[65, 66, 56, 55, 76, 89]
['BMW', 'Mercedes', 'Volvo']
['BMW', 'Mercedes', 'Volvo']
['Volvo', 'BMW', 'Mercedes']


In [43]:
#copy list
thislist=['Mercedes','BMW','Volvo']
mylist=thislist.copy()
print(mylist)

#join list
list1=['Mercedes','BMW','Volvo']
list2=['Hunda','Nissan','Toyota']
list3=list1+list2
print(list3)

#using extend function
list1=[6,9,6]
list2=['s','n','s']
list1.extend(list2)
print(list1)

['Mercedes', 'BMW', 'Volvo']
['Mercedes', 'BMW', 'Volvo', 'Hunda', 'Nissan', 'Toyota']
[6, 9, 6, 's', 'n', 's']


In [44]:
# TUPLES
thistuple=('Mercedes','BMW','Volvo')
print(thistuple)

# Allows duplicates
thistuple=('Mercedes','BMW','Volvo','Hunda')
print(thistuple)

#tuple length
thistuple=('Mercedes','BMW','Volvo')
print(len(thistuple))

# Create Tuple With One Item
# *** for adding only one item in tuple use comma after that item otherwise it is not considered as tuple
thistuple=('car',)
print(thistuple)

# tuple can contain different datatypes
mytuple=(23,"orange", True, 69.69)
print(mytuple)

#tuple constructor
tuple1=tuple(('Mercedes','BMW','Volvo'))
print(tuple1)

('Mercedes', 'BMW', 'Volvo')
('Mercedes', 'BMW', 'Volvo', 'Hunda')
3
('car',)
(23, 'orange', True, 69.69)
('Mercedes', 'BMW', 'Volvo')


In [48]:
# Access tple items
# by refering the index num
mytuple=('Mercedes','BMW','Volvo')
print(mytuple[1])

# Negative indexing
mytuple=('Mercedes','BMW','Volvo')
print(mytuple[-1])

# Range of indexs
thistuple=('Mercedes','BMW','Volvo','Hunda')
print(thistuple[1:4])

# Check if Item Exists
mytuple=('Mercedes','BMW','Volvo','Hunda')
if 'BMW' in mytuple:
  print("yes, 'BMW' is in the tuple")

BMW
Volvo
('BMW', 'Volvo', 'Hunda')
yes, 'BMW' is in the tuple


In [49]:
# Update tuple
# *** chnaging tuples in list and back them in tuple***

#changing specific value
x=('Mercedes','BMW','Volvo','Hunda')
y=list(x)
y[3]='Hundai'
x=tuple(y)
print(x)

# addding item to tuple

# 1. change them in list:
x=('Mercedes','BMW','Volvo','Hunda')
y=list(x)
y.append('Nissan')
x=tuple(y)
print(x)

# 2. by adding two tuples:
tuple1=('Mercedes','BMW','Volvo','Hunda')
tuple2=('kiwi','leeche')
tuple3=tuple1+tuple2
print(tuple3)

# Removing items
# tuple -> list -> tuple
mytuple=('Mercedes','BMW','Volvo','Hunda')
thislist=list(mytuple)
thislist.remove('BMW')
mytuple=tuple(thislist)
print(mytuple)

#delete tuple
tuple1=(1,2,3,4,5)
del tuple1
print(tuple1)# error will occured bcuz tuple is deleted


('Mercedes', 'BMW', 'Volvo', 'Hundai')
('Mercedes', 'BMW', 'Volvo', 'Hunda', 'Nissan')
('Mercedes', 'BMW', 'Volvo', 'Hunda', 'kiwi', 'leeche')
('Mercedes', 'Volvo', 'Hunda')


NameError: name 'tuple1' is not defined

In [53]:
# Unpack tuple
fruits=('strawberry','apple','mango')
(pink,red,yellow)=fruits
print(pink,red,yellow)

#Using Asterisk*
fruits=('strawberry','apple','mango','orange','kiwi','grapes')
(pink,*red,yellow)=fruits
print(pink)
print(red)
print(yellow)

strawberry apple mango
strawberry
['apple', 'mango', 'orange', 'kiwi']
grapes


In [54]:
#Loop Tuples

#for loop
mytuple=('Mercedes','BMW','Volvo','Hunda')
for x in mytuple:
  print(x)

#Loop Through the Index Numbers
thistuple=('Mercedes','BMW','Volvo','Hunda')
for i in range(len(thistuple)):
  print(thistuple[i])

#Using a While Loop
thistuple=('Mercedes','BMW','Volvo','Hunda')
i=0
while i<len(thistuple):
  print(thistuple[i])
  i=i+1

Mercedes
BMW
Volvo
Hunda
Mercedes
BMW
Volvo
Hunda
Mercedes
BMW
Volvo
Hunda


In [55]:
#Join Tuples
# by + operator
tuple1=('Mercedes','BMW','Volvo','Hunda')
tuple2=('Hundai','Hunda','Nissan','Toyota')
tuple3=tuple1+tuple2
print(tuple3)

# by * operator
tuple1=('Mercedes','BMW','Volvo','Hunda')
tuple2=tuple1 * 2
print(tuple2)

('Mercedes', 'BMW', 'Volvo', 'Hunda', 'Hundai', 'Hunda', 'Nissan', 'Toyota')
('Mercedes', 'BMW', 'Volvo', 'Hunda', 'Mercedes', 'BMW', 'Volvo', 'Hunda')


In [58]:
# Sets
thisset = {'Mercedes', 'BMW', 'Volvo', 'Hunda'}
print(thisset)

# Duplicate value will be ignored
myset = {'Mercedes', 'BMW', 'Volvo', 'Hunda'}
print(myset)

# True and 1, False and 0 are considered the same value
myset = {'Mercedes', 'BMW', 'Volvo', 'Hunda', 2, 1, True}
print(myset)

myset = {'Mercedes', 'BMW', 'Volvo', 'Hunda', 2, False, 0}
print(myset)

# Length of the set
thisset = {'Mercedes', 'BMW', 'Volvo', 'Hunda'}
print(len(thisset))

# Type of the set
thisset = {'Mercedes', 'BMW', 'Volvo', 'Hunda'}
print(type(thisset))

# Set constructor
set1 = set(('Mercedes', 'BMW', 'Volvo', 'Hunda'))
print(set1)


{'Mercedes', 'BMW', 'Volvo', 'Hunda'}
{'Mercedes', 'BMW', 'Volvo', 'Hunda'}
{1, 'BMW', 2, 'Volvo', 'Mercedes', 'Hunda'}
{False, 2, 'BMW', 'Volvo', 'Mercedes', 'Hunda'}
4
<class 'set'>
{'Mercedes', 'BMW', 'Volvo', 'Hunda'}


In [ ]:
#access set
#*** can not access ny index number***

#via loop
set1={'Pakistan','Oman','Turkey'}
for x in set1:
  print(x)

#returning true (for returning false use not in)
set1={'Pakistan','Oman','Turkey'}
print('Pakistan' in set1)

Pakistan
Turkey
Oman
True


In [59]:
# Add set items

# ***add items*** ---> add()
thisset={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
thisset.add('Toyota')
print(thisset)

#add sets----> update() **the update will add list,tuple,dict to set as well.
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'lahore','kasur','multan'}
set1.update(set2)
print(set1)

#Remove set items
#***remove() *** if the item is not present it will raise an error
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set1.remove('BMW')
print(set1)

#***discard() *** if the item is not present it will raise an error
set2={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2.discard('BMW')
print(set2)

#pop() ----> for removing anyrandom number
myset={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
myset.pop()
print(myset)

# clear() -----> for emties the set
thisset={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
thisset.clear()
print(thisset)

# del() -----> for delt the set
thisset={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
del thisset
print(thisset) # error occurs becuz the set is deleted

{'BMW', 'Toyota', 'Hunda', 'Volvo', 'Mercedes'}
{'BMW', 'Volvo', 'kasur', 'multan', 'Mercedes', 'lahore', 'Hunda'}
{'Mercedes', 'Volvo', 'Hunda'}
{'Mercedes', 'Volvo', 'Hunda'}
{'BMW', 'Volvo', 'Hunda'}
set()


NameError: name 'thisset' is not defined

In [ ]:
# loop set
myset={'rain','water','air'}
for x in myset:
  print(x)

rain
water
air


In [60]:
# join sets

# ***union() ---->joins all items from both sets also you can use | opertaor
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set3=set1.union(set2)
print(set3)

#update() ---->inserts all items from one set into another
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set1.update(set2)
print(set1)

#intersection --->same elements of set also & opertaor used for it
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set3=set1.intersection(set2)
print(set3)

# intersection_update ----> update the first set
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set1.intersection(set2)
print(set1)

#difference() --->  return new set that will contain items from first set that are not present in other set
# *** you can also use - for this
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set3=set1.difference(set2)
print(set3)
#diifference_update ----> update first set
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set1.difference(set2)
print(set1)

#symmetric_difference ----> also ^ is used for this
# ***will keep only the elements that are NOT present in both sets***
set1={'Mercedes', 'BMW', 'Volvo', 'Hunda'}
set2={'Hundai','Hunda','Nissan','Toyota'}
set1.symmetric_difference(set2)
print(set1)

{'BMW', 'Toyota', 'Hunda', 'Hundai', 'Volvo', 'Mercedes', 'Nissan'}
{'BMW', 'Toyota', 'Hunda', 'Hundai', 'Volvo', 'Mercedes', 'Nissan'}
{'Hunda'}
{'Mercedes', 'BMW', 'Volvo', 'Hunda'}
{'Mercedes', 'BMW', 'Volvo'}
{'Mercedes', 'BMW', 'Volvo', 'Hunda'}
{'Mercedes', 'BMW', 'Volvo', 'Hunda'}


In [61]:
#Dictionaries
mydict={'brand':'Mercedes','model':'G-Wagon','year':2020}
print(mydict)

#Dictionary Items
mydict={'brand':'Mercedes','model':'G-Wagon','year':2020}
print(mydict['brand'])

#dictionary length
mydict={'brand':'Mercedes','model':'G-Wagon','year':2020}
print(len(mydict))

#dictionary constructor
thisdict=dict(brand='Mercedes',model='G-Wagon',year=2020)
print(thisdict)



{'brand': 'Mercedes', 'model': 'G-Wagon', 'year': 2020}
Mercedes
3
{'brand': 'Mercedes', 'model': 'G-Wagon', 'year': 2020}


In [62]:
#access items
mydict={'brand':'Mercedes','model':'G-Wagon','year':2020}
x=mydict['year']
print(x)

#Get Keys
mydict={'brand':'Mercedes','model':'G-Wagon','year':2020}
x=mydict.keys()
print(x)
#adding new item to this dictionary
mydict['colour']='black'
print(x)

#get values
thisdict={'name':'amna','class':'seven','sec':'b '}
x=thisdict.values()
print(x)

#cheaking for a specifiv key exits
thisdict={'name':'amna','class':'seven','sec':'b '}
if 'name' in thisdict:
  print('yes, name is present' )

2020
dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'colour'])
dict_values(['amna', 'seven', 'b '])
yes, name is present


In [1]:
# Change Dictionary Items

#Changing specific Values
thisdict={'name':'Azan','class':'third','sec':'a '}
thisdict['class']='first'
print(thisdict)

#Update Dictionary
thisdict={'name':'Azan','class':'third','sec':'a '}
thisdict.update({'name':'shan'})
print(thisdict)

{'name': 'Azan', 'class': 'first', 'sec': 'a '}
{'name': 'shan', 'class': 'third', 'sec': 'a '}


In [2]:
#Remove Dictionary Items
#pop() ----> removes item with specific key
thisdict={'name':'Azan','class':'third','sec':'a '}
thisdict.pop('class')
print(thisdict)

#popitem() ------> removes last item of dict
thisdict={'name':'Azan','class':'third','sec':'a '}
thisdict.popitem()
print(thisdict)

#clear() ----> emties the dict
thisdict={'name':'Azan','class':'third','sec':'a '}
thisdict.clear()
print(thisdict)

#del keyword ----> removes the item with the specified key name
thisdict={'name':'Azan','class':'third','sec':'a '}
del thisdict['name']
print(thisdict)
#*** del is also used to del the dict***
thisdict={'name':'Azan','class':'third','sec':'a '}
del thisdict
print(thisdict) # error will occur bcuz dict is deleted

{'name': 'Azan', 'sec': 'a '}
{'name': 'Azan', 'class': 'third'}
{}
{'class': 'third', 'sec': 'a '}


NameError: name 'thisdict' is not defined

In [3]:
# Loop Dictionaries

#for getting dict keys
thisdict={'name':'Azan','class':'third','sec':'a '}
for x in thisdict:
  print(x)

# for getting dict values
thisdict={'name':'Azan','class':'third','sec':'a '}
for x in thisdict.values():
  print(x)
  # *** you can access both keys and values using items()

#Copy Dictionaries
#using copy()
dict1={'name':'Azan','class':'third','sec':'a '}
dict2=dict1.copy()
print(dict2)

name
class
sec
Azan
third
a 
{'name': 'Azan', 'class': 'third', 'sec': 'a '}


In [4]:
#Nested Dictionaries
#*** dictionary contaning dictionary***
topdict={
    'dict1':{'name':'Azan','class':'third'},
    'dict2':{'name':'shan','class':'six'},
   ' dict3':{'name':'manan','class':'two'}
}
print(topdict)

#adding three dictionary into new dictionary
dict1={'pear':'green','weigth':'1 kg'}
dict2={'apple':'red','weigth':'2 kg'}
dict3={'mango':'yellow','weigth':'2 kg'}

mydict={
    'dict1':dict1,
    'dict2':dict2,
    'dict3':dict3
}
print(mydict)

#Access Items in Nested Dictionaries
thisdict={
    'dict1':{'name':'haram','year':2004},
    'dict2':{'name':'shan','year':2004},
    'dict3':{'name':'shan','year':2004}
}
print(thisdict['dict2']['name'])

#Loop Through Nested Dictionaries
thisdict={
    'dict1':{'name':'haram','year':2004},
    'dict2':{'name':'shan','year':2004},
    'dict3':{'name':'shan','year':2004}
}
for x, obj in thisdict.items():
  print(x)
  for y in obj:
    print(y+ ':',obj[y])


{'dict1': {'name': 'Azan', 'class': 'third'}, 'dict2': {'name': 'shan', 'class': 'six'}, ' dict3': {'name': 'manan', 'class': 'two'}}
{'dict1': {'pear': 'green', 'weigth': '1 kg'}, 'dict2': {'apple': 'red', 'weigth': '2 kg'}, 'dict3': {'mango': 'yellow', 'weigth': '2 kg'}}
shan
dict1
name: haram
year: 2004
dict2
name: shan
year: 2004
dict3
name: shan
year: 2004


In [5]:
# if else
a=65
b=56
if a>b :
  print('a is greater than b')

# Elif
a=77
b=77
if b<a:
  print('a is greater than b')
elif a==b:
  print('a and b are equal')

#else
a=28
b=45
if a>b:
  print('a is greater than b')
elif b>a:
  print('b is greater than a')
else:
  print('a and b are equal')

#Short Hand If
a=45
b=34
if a>b: print('a is greater than b')

#Short Hand If ... Else
a=234
b=876
print('b') if b>a else print('a and b are equal') if a==b else print('a')

#logical operators
#And
a=67
b=34
c=27
if a>b and c<b:
  print('both statments are true')

#or
a=89
b=56
c=93
if a==b or c>a:
  print('one statment is true')

#Not
a=76
b=60
if not a<b:
  print('b is not greater than a')

#nestes if
a=30
if a>10:
  print('a is greater than 10')
  if a>20:
    print('a is greater than 20')
  else:
    print('but not above 25')



a is greater than b
a and b are equal
b is greater than a
a is greater than b
b
both statments are true
one statment is true
b is not greater than a
a is greater than 10
a is greater than 20


In [ ]:
#LOOPS

#While Loops
i=0
while i<8:
  print(i)
  i +=1

print('.....')
#break Statement
i=1
while i<8:
    print(i)
    if i >= 5:
      break
    i +=1

print('......')
#The continue Statement
i=0
while i<10:
  i += 1
  if i == 5:
    continue
  print(i)

print('......')
#The else Statement
i=0
while i<8:
  print(i)
  i +=1
else:
  print('i is now greater than 8')

0
1
2
3
4
5
6
7
.....
1
2
3
4
5
......
1
2
3
4
6
7
8
9
10
......
0
1
2
3
4
5
6
7
i is now greater than 8


In [ ]:
# for loop
fruits=['mango','orange','apple']
for x in fruits:
  print(x)

print('....')
#Looping Through a String
fruits=['mango','orange','apple']
for x in 'apple':
  print(x)

print('.....')
#The break Statement
fruits=['mango','orange','apple','pear']
for x in fruits:
  print(x)
  if x == 'apple':
    break

print('.....')
#The continue Statement
fruits=['mango','orange','apple','pear']
for x in fruits:
  print(x)
  if x == 'orange':
    continue

print('.....')
#The range() Function
for x in range(5):
  print(x)

print('....')
#Else in For Loop
for x in range(2,24,3):
  print(x)
else:
  print('all done')

print('......')
#Nested Loops
colour=['red','yellow','green']
fruits=['apple','mango','pear']
for x in colour:
  for y in fruits:
    print(x,y)

#pass Statement
for x in fruits:
  pass

mango
orange
apple
....
a
p
p
l
e
.....
mango
orange
apple
.....
mango
orange
apple
pear
.....
0
1
2
3
4
....
2
5
8
11
14
17
20
23
all done
......
red apple
red mango
red pear
yellow apple
yellow mango
yellow pear
green apple
green mango
green pear


In [6]:
#Python Functions
def my_func():
  print('hello from a function')
my_func()

#ARGUMENTS
def my_func(name):
      print(name+'Azan')
my_func('Muhammad')
my_func('Good')
my_func('bad')
my_func('Legend')

#Arbitrary Arguments, *args
def my_func(*child):
  print('The youngest child is ', child[3])
my_func('azan','anas','ahmed','haziq')

#Keyword Arguments
def my_func(child1,child2,child3,child4):
  print('The youngest child is ', child4)
my_func(child1='Azan',child2='anas',child3='ahmed',child4='haziq')

#Default Parameter Value
def my_func(c='pakistan'):
  print('i am from ',c)
my_func('UAE')
my_func('Japan')
my_func()

#Passing a List as an Argument
def my_func(fruits):
  for x in fruits:
    print(x)
fruits=['apple','mango','orange']
my_func(fruits)

#Return Values
def my_func(x):
  return x + 5
print(my_func(5))

print('.....')
#recursion
def tri_recursion(x):
  if (x >0):
    result=x + tri_recursion(x-1)
    print(result)
  else:
    result=0
  return result
print('th recursion value is :')
tri_recursion(6)


hello from a function
MuhammadAzan
GoodAzan
badAzan
LegendAzan
The youngest child is  haziq
The youngest child is  haziq
i am from  UAE
i am from  Japan
i am from  pakistan
apple
mango
orange
10
.....
th recursion value is :
1
3
6
10
15
21


21

In [ ]:
# lambda -----> small anonymous function
x=lambda a: a+5
print(x(5))

x= lambda a,b,c:a*b*c
print(x(2,6,5))

# for doubling a num
def my_func(n):
  return lambda a: a*n
double_num = my_func(2)
print(double_num(22))

10
60
44


In [7]:
#OOP
#Python Arrays
#accessing via index
fruits=['volvo','mercedes','bmw']
x=fruits[1]
print(x)

#for loop
arr=['volvo','mercedes','bmw']
for x in arr:
  print(x)

#Adding Array Elements
myarr=['volvo','mercedes','bmw']
myarr.append('mango')
print(myarr)

#Removing Array Elements
myarr.pop(2)
print(myarr)

mercedes
volvo
mercedes
bmw
['volvo', 'mercedes', 'bmw', 'mango']
['volvo', 'mercedes', 'mango']


In [8]:
#Classes and Objects

class theclass:
  x=6
  y=9
obj1=theclass()
obj2=theclass()
print(obj1.x,obj2.y)

#The __init__() Function ----> to assign values
class myclass:
  def __init__(self,name,age):
    self.name=name
    self.age=age
obj1= myclass('Azan',20)
print(obj1.name,obj1.age)

# __str__() function
class Person:
  def __init__(myself,theclass,sec):
    myself.theclass= theclass
    myself.sec = sec
  def __str__(myself):
    return f"{myself.theclass}({myself.sec})"
person1=Person(6,'A')
print(person1)

#Object Methods
class City:
  def __init__(self,name,loc):
    self.name=name
    self.loc = loc
  def myfunc(self):
    print('The name of my city is ' + self.name)
s1=City('Karachi','Pakistan')
s1.myfunc()



6 9
Azan 20
6(A)
The name of my city is Karachi


In [1]:
# Python Inheritance
#creating parent class
class Teacher:
  def __init__(self,firstname,lastname):
    self.firstname=firstname
    self.lastname=lastname
  def myfunc(self):
    print(self.firstname,self.lastname)
t1=Teacher('Muhammad','Azan')
t1.myfunc()

#creating child class ** send the parent class as a parameter**
class Student(Teacher):
  pass
s1=Student('Shan-e-','ALI')
s1.myfunc()

#Add the __init__() Function
class Student(Teacher):
  def __init__(self,firstname,lastname):
    Teacher.__init__(self,firstname,lastname)
s2=Student('Abdul','Manan')
s2.myfunc()

#Use the super() Function **he child class inherit all the methods and properties from its parent***
class Student(Teacher):
  def __init__(self,firstname,lastname):
    super().__init__(firstname,lastname)
s3=Student('Waqar','Zahid')
s3.myfunc()

#Add Properties
class Employee:
  def __init__(self,fname,lname):
    self.fname=fname
    self.lname=lname
  def myfunc(self):
    print(self.fname,self.lname)
class Teacher(Employee):
  def __init__(self,fname,lname,year):
    super().__init__(fname,lname)
    self.graduationyear = year
t1=Teacher('SIR','Sajid',2023)
t1.myfunc()
print(t1.graduationyear)

Muhammad Azan
Shan-e- ALI
Abdul Manan
Waqar Zahid
SIR Sajid
2023


In [2]:
# Python Iterators
mylist=['volvo','mercedes','bmw']
myit=iter(mylist)
print(next(myit))
print(next(myit))
print(next(myit))

print('.....')
#Looping Through an Iterator
mylist=['volvo','mercedes','bmw']
for x in mylist:
  print(x)

print('.....')
#Create an Iterator in class
class Evennum:
  def __iter__(self):
    self.e=2
    return self
  def __next__(self):
    x=self.e
    self.e +=2
    return x
myclass=Evennum()
myiter=iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

print('......')
#StopIteration
class Oddnum:
  def __iter__(self):
    self.o=1
    return self
  def __next__(self):
    if self.o <=13:
      x=self.o
      self.o += 2
      return x
    else:
      raise StopIteration
myclass=Oddnum()
iter=iter(myclass)

for x in myclass:
  print(x)

volvo
mercedes
bmw
.....
volvo
mercedes
bmw
.....
2
4
6
8
10
......
1
3
5
7
9
11
13


In [3]:
# Python Polymorphism
class Lion:
  def __init__(self,colour,size):
    self.colour=colour
    self.size=size
  def sound(self):
    print('roar')
class Dog:
  def __init__(self,colour,size):
    self.colour=colour
    self.size=size
  def sound(self):
    print('bark')
class Cat:
  def __init__(self,colour,size):
    self.colour=colour
    self.size=size
  def sound(self):
    print('meow')

mylion=Lion('Yellow','Big')
mydog=Dog('black','avrg')
mycat=Cat('brown','Small')

for x in(mylion,mydog,mycat):
 x.sound()

print('.....')
#Inheritance Class Polymorphism
class Animal:
  def __init__(self,colour,size):
    self.colour=colour
    self.size=size

class Lion(Animal):
  def sound(self):
    print('roar')

class Dog(Animal):
  def sound(self):
    print('bark')

class Cat(Animal):
  def sound(self):
    print('meow')

mylion=Lion('Yellow','Big')
mydog=Dog('black','avrg')
mycat=Cat('brown','Small')

for x in(mylion,mydog,mycat):
 print(x.colour)
 print(x.size)
 x.sound()

roar
bark
meow
.....
Yellow
Big
roar
black
avrg
bark
brown
Small
meow


In [1]:
### Numpy

In [2]:
### importing the libarary
import numpy as np

In [5]:
#creating an array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
#creating an array of zero
arr = np.zeros((3, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
#creating an array of ones
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#creating an empty list
arr = np.empty((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#array with filled with specific number
arr = np.full((3, 3), 8)
print(arr)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [10]:
#array of evenly spread number
arr = np.arange(0, 10, 3)
print("arange:",arr)

arange: [0 3 6 9]


In [11]:
#generate numbers with evenly distributed space in a range
arr = np.linspace(0, 10, 2)
print(arr)
arr = np.linspace(0, 10, 3)
print(arr)
arr = np.linspace(0, 10, 5)
print(arr)

[ 0. 10.]
[ 0.  5. 10.]
[ 0.   2.5  5.   7.5 10. ]


In [12]:
#Creates an array with logarithmically spaced values
arr = np.logspace(1, 3, 3)
print(arr)

[  10.  100. 1000.]


In [13]:
#create an identity martix
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#create array of randam number ranging 0-1
arr = np.random.random((3, 3))
print(arr)

[[0.55710134 0.31590162 0.0582082 ]
 [0.53848696 0.66873372 0.84250735]
 [0.43924607 0.03024908 0.40284994]]


In [15]:
#create array of randam number of specified range
arr = np.random.randint(0, 5, (3, 3))
print(arr)

[[2 4 2]
 [1 2 4]
 [0 4 0]]


In [16]:
## Array Manipulation
#reshape array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = arr.reshape((3, 2))
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
#flatten an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = arr.ravel()
print(arr)

[1 2 3 4 5 6]


In [18]:
# transpose of array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = arr.transpose()
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# swapping of axis in higher dimension
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr = arr.swapaxes(0, 1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [20]:
# joining array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[1 2 3 4 5 6]


In [21]:
# stack arrays on each other
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
# split array into sub array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.split(arr, 2)
print(arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [23]:
# horizontly stacks array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [24]:
# veritaclly stack arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
## Array Information
# shape of array
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
shape = arr.shape
print("shape:", shape)

shape: (3, 3)


In [26]:
# size of array
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
size = arr.size
print("size:", size)

size: 9


In [27]:
# data type of array
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
dtype = arr.dtype
print("dtype:", dtype)

dtype: int32


In [28]:
# dimension of array
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
ndim = arr.ndim
print("ndim:", ndim)

ndim: 2


In [29]:
# size of one array element in bytes.
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
itemsize = arr.itemsize
print("itemsize1:", itemsize)

arr = np.array([[1, 2, 3], [4, 5, 6]])
itemsize = arr.itemsize
print("itemsize2:", itemsize)

arr = np.array([[1, 2.1, 3], [4.0, 5.7, 6.8]])
itemsize = arr.itemsize
print("itemsize3:", itemsize)

arr = np.array([[1, 2, 3], [4.0, 5.7, 6.8]])
itemsize = arr.itemsize
print("itemsize4:", itemsize)

itemsize1: 4
itemsize2: 4
itemsize3: 8
itemsize4: 8


In [30]:
# bytes consumed by the elements of the array.
arr = np.array([1, 2, 3])
nbytes = arr.nbytes
print("nbytes:", nbytes)

nbytes: 12


In [31]:
## Array Operations
# add two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.add(arr1, arr2)
print(arr)

[5 7 9]


In [32]:
# subtract two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.subtract(arr1, arr2)
print(arr)

[-3 -3 -3]


In [33]:
# multiply two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.multiply(arr1, arr2)
print(arr)

[ 4 10 18]


In [34]:
# divide two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.divide(arr1, arr2)
print(arr)

[0.25 0.4  0.5 ]


In [35]:
# taking power of array
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
arr = np.power(arr1, arr2)
print(arr)

[1 4 9]


In [36]:
# dot product of array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
product = np.dot(arr1, arr2)
print(product)

32


In [37]:
# Matrix product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
product = np.matmul(arr1, arr2)
print(product)

[[19 22]
 [43 50]]


In [38]:
# Tensor dot product of two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
product = np.tensordot(arr1, arr2, axes=0)
print(product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [39]:
# square function
arr = np.array([0, 1, 2, 3, 4])
arr = np.square(arr)
print(arr)

[ 0  1  4  9 16]


In [40]:
# square root function
arr = np.array([0, 1, 2, 3, 4])
arr = np.sqrt(arr)
print(arr)

[0.         1.         1.41421356 1.73205081 2.        ]


In [41]:
## Statistical Functions
# mean
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.mean(arr)
print(val)

5.5


In [42]:
# median
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.median(arr)
print(val)

5.5


In [43]:
# standard deviation
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.std(arr)
print(val)

2.8722813232690143


In [44]:
# Varience
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.var(arr)
print(val)

8.25


In [45]:
# min value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.min(arr)
print(val)

1


In [46]:
# max value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.max(arr)
print(val)

10


In [47]:
# index of min value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.argmin(arr)
print(val)

0


In [48]:
# index of max value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
val = np.argmax(arr)
print(val)

9


In [49]:
# percentile
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
val = np.percentile(arr, 50)
print(val)

5.0


In [54]:
# Logical Functions
arr = np.array([True, False, True, True, False])
arr1 = np.array([True, True, False, False, True])
arr2 = np.array([False, True, False, True, False])

In [51]:
# check if all the values are true
result = np.all(arr)
print(result)

False


In [52]:
# check if there is any true value
result = np.any(arr)
print(result)

True


In [55]:
# and operation
result = np.logical_and(arr1, arr2)
print(result)

[False  True False False False]


In [56]:
# or opertaion
result = np.logical_or(arr1, arr2)
print(result)

[ True  True False  True  True]


In [57]:
# not operator
result = np.logical_not(arr)
print(result)

[False  True False False  True]


In [58]:
# XOR operation
result = np.logical_xor(arr1, arr2)
print(result)

[ True False False  True  True]


In [59]:
## Linear Algebra
# dot product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
val = np.dot(arr1, arr2)
print(val)

32


In [60]:
# vector dot product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
val = np.vdot(arr1, arr2)
print(val)

32


In [61]:
# inner product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
val= np.inner(arr1, arr2)
print(val)

32


In [62]:
# outer product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.outer(arr1, arr2)
print(arr)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [63]:
# determinant
mat1 = np.array([[1, 2], [3, 4]])
val = np.linalg.det(mat1)
print(val)

-2.0000000000000004


In [64]:
## Random Sampling
# generates random value
arr = np.random.rand(3, 2)
print(arr)

[[0.30251361 0.90222523]
 [0.65160014 0.66690482]
 [0.1659964  0.00215796]]


In [65]:
# generates random value from the standard normal distribution
arr = np.random.randn(3, 2)
print(arr)

[[ 0.52103826  1.35319759]
 [ 1.52747944  2.74930938]
 [ 0.11462636 -1.03527936]]


In [66]:
# generate random value in a range
arr = np.random.randint(1, 10, size=(3, 2))
print(arr)

[[2 1]
 [5 7]
 [5 3]]


In [67]:
# choose a random  value from a list
arr = np.random.choice([1, 2, 3, 4, 5], size=(3, 2))
print(arr)

[[2 4]
 [5 3]
 [3 5]]


In [68]:
# randomly shuffle a value in a listarr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[2 1 4 5 3]


In [69]:
# Randomly permute a sequence, or return a permuted range
arr = np.random.permutation(4)
print(arr)

[0 3 2 1]


In [70]:
## Set Operations
# unique elements in an  array
arr1 = np.array([1, 2, 2, 3, 4])
val = np.unique(arr1)
print(val)

[1 2 3 4]


In [71]:
# intersection of two arrays.
arr1 = np.array([1, 2, 2, 3, 4])
arr2 = np.array([3, 4, 4, 5, 6])
intersection = np.intersect1d(arr1, arr2)
print("intersect1d:", intersection)

intersect1d: [3 4]


In [72]:
# union of two arrays
arr1 = np.array([1, 2, 2, 3, 4])
arr2 = np.array([3, 4, 4, 5, 6])
union = np.union1d(arr1, arr2)
print("union1d:", union)

union1d: [1 2 3 4 5 6]


In [73]:
# difference of  two arrays
arr1 = np.array([1, 2, 2, 3, 4])
arr2 = np.array([3, 4, 4, 5, 6])
set_difference = np.setdiff1d(arr1, arr2)
print("setdiff1d:", set_difference)

setdiff1d: [1 2]


In [74]:
# exclusive-or of two arrays.
arr1 = np.array([1, 2, 2, 3, 4])
arr2 = np.array([3, 4, 4, 5, 6])
set_xor = np.setxor1d(arr1, arr2)
print("setxor1d:", set_xor)

setxor1d: [1 2 5 6]


In [3]:
#Pandas
import pandas as pd

# Creating DataFrame
data = {
    'Name': ['Hanzalah', 'Shan', 'Farzam'],
    'Age': [25, 30, 35],
    'City': ['Lahore', 'Islamabad', 'Multan']
}
df = pd.DataFrame(data)
print("DataFrame from dictionary:\n", df)

# Viewing Data
print("Head of DataFrame:\n", df.head())
print("Tail of DataFrame:\n", df.tail())
print("DataFrame info:\n", df.info())
print("DataFrame description:\n", df.describe())
print("DataFrame shape:", df.shape)
print("DataFrame columns:", df.columns)
print("DataFrame index:", df.index)

# Selecting Data
print("Select a single column:\n", df['Name'])
print("Select multiple columns:\n", df[['Name', 'Age']])
print("Select rows by index:\n", df.iloc[0])
print("Select rows by label:\n", df.loc[0])
print("Select rows and columns by label:\n", df.loc[0, 'Name'])
print("Select rows and columns by condition:\n", df[df['Age'] > 30])

# Adding/Removing Data
df['Country'] = ['Pakistan', 'USA', 'UK']
print("After adding a column:\n", df)

df = df.drop(columns=['Country'])
print("After dropping a column:\n", df)


# Handling Missing Data
df.loc[1, 'Age'] = None
print("DataFrame with missing value:\n", df)

df_filled = df.fillna(0)
print("After filling missing values:\n", df_filled)

df_dropped = df.dropna()
print("After dropping missing values:\n", df_dropped)

# Grouping Data
grouped = df.groupby('City')
print("Grouped by City with mean values:\n", grouped)

# Merging Data
data1 = {'key': ['A', 'B', 'C'], 'value': [1, 2, 3]}
data2 = {'key': ['A', 'B', 'D'], 'value': [4, 5, 6]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

merged_inner = pd.merge(df1, df2, on='key')
print("Inner merge:\n", merged_inner)

merged_outer = pd.merge(df1, df2, on='key', how='outer')
print("Outer merge:\n", merged_outer)

# Concatenating Data
df3 = pd.concat([df1, df2], axis=0)
print("Concatenated along rows:\n", df3)

df4 = pd.concat([df1, df2], axis=1)
print("Concatenated along columns:\n", df4)

# Pivot Tables
pivot_data = {
    'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one', 'two', 'two', 'one', 'one'],
    'C': ['small', 'large', 'small', 'small', 'large', 'small'],
    'D': [1, 2, 2, 3, 3, 4]
}
df_pivot = pd.DataFrame(pivot_data)
pivot_table = df_pivot.pivot_table(values='D', index=['A', 'B'], columns=['C'], aggfunc='sum')
print("Pivot table:\n", pivot_table)

# Sorting Data
sorted_df = df.sort_values(by='Age')
print("DataFrame sorted by Age:\n", sorted_df)

# Applying Functions
df['Age_plus_10'] = df['Age'].apply(lambda x: x + 10 if pd.notnull(x) else x)
print("After applying function to Age column:\n", df)

DataFrame from dictionary:
        Name  Age       City
0  Hanzalah   25     Lahore
1      Shan   30  Islamabad
2    Farzam   35     Multan
Head of DataFrame:
        Name  Age       City
0  Hanzalah   25     Lahore
1      Shan   30  Islamabad
2    Farzam   35     Multan
Tail of DataFrame:
        Name  Age       City
0  Hanzalah   25     Lahore
1      Shan   30  Islamabad
2    Farzam   35     Multan
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
DataFrame info:
 None
DataFrame description:
         Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0
DataFrame shape: (3, 3)
DataFrame columns: Index(['Name', 'Age', 'City'], dtype='object')
DataFrame index: 